### PR TITLE
Disables TTS (read aloud) for DWDS custom app

### PR DESCRIPTION
**Pull request by gremid**
The results of the builtin text-to-speech service are not good enough at the moment, so we would prefer to disable this feature until we found a way to control which parts of a DWDS article are read and in which order.

### CODE REVIEW

**Comment by kelson42** [comment]
@gouri-panda Do we have any feature allowing to disable TTS based on info.json?!

**Comment by gouri-panda** [comment]
@kelson42 Yes, we do have that feature.

**Comment by gouri-panda** [comment]
>Why is that not documented in the README.md?

I'll add that.
> Do we have other options of that kind?

https://github.com/kiwix/kiwix-android/blob/1b879006958db11b6070c54013c8e7da126ba7da/buildSrc/src/main/kotlin/custom/CustomApps.kt#L47-L54

**Comment by kelson42** [comment]
>> Why is that not documented in the README.md?
> I'll add that

Thanks! It's really important that all possible options/properties which can be put in the info.json are clearly explained and understandable.

**Comment by gouri-panda** [comment]
@gremid Thank you! But unfortunately, we can't merge this at the moment. But I've pushed your code to the `dwds` tag.

**Comment by kelson42** [comment]
@gouri-panda Please open a PR for the dwds branch.

**Comment by gremid** [comment]
@gouri-panda @kelson42 When will the changes be published then?

**Comment by gouri-panda** [comment]
@gremid After https://github.com/kiwix/kiwix-android/pull/3526, I think we're good to merge. Also, we're already published your change into play store https://github.com/kiwix/kiwix-android-custom/actions/runs/6795725744 .

**Pull request closed without merging**
