### PR TITLE
Dwds creation

### PR DESCRIPTION
**Pull request by gouri-panda**
Fixes kiwix/kiwix-android-custom#107

Created `Dwds` folder and updated env in order to support the authentication. Updated the Kiwix app icon just for now.

### CODE REVIEW

**Review by MohitMaliFtechiz — CHANGES_REQUESTED** [review]
@gouri-panda, Why we are not adding `icon_master.png` and `mipmap-anydpi-v26` folder? We should add `icon_master.png` for the round logo, and `mipmap-anydpi-v26` like we are adding for other applications.

Screenshot from 2023-10-02 17-25-26

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz At that moment I don't have any round logo and we'll also replace it with the new one. I'll add the `mipmap-anydpi-v26`.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz At that moment I don't have any round logo and we'll also replace it with the new one.

Okay, please add the default logo for now in `icon-master.png` to avoid any future errors we will replace it when we have the correct logo.

**Review by MohitMaliFtechiz — DISMISSED** [review]
@gouri-panda Thanks for the quick fixes, now it's LGTM :tada::tada:.

**Review by kelson42 — APPROVED** [review]
I don't have tested... but looks good. Will merge when #106 is fixed. thx

**Pull request merged**
