### PR TITLE
changed icon for mini Wikimed

### LINKED ISSUE #7: Replace icon/favicon.png in mini Wikimed
icon

### PR DESCRIPTION
**Pull request by utkarshmttl**
Resolves #7

### CODE REVIEW

**Comment by kelson42** [comment]
we need to reuse the button style like in current version.

**Comment by utkarshmttl** [comment]
Sorry, I do not understand. Do you mean the styling of the icon (curved edges)?

**Comment by kelson42** [comment]
yes

**Comment by kelson42** [comment]
To me it looks like you have put more shadow than in the previous version, Can you just please put the logo in the previous button template/background?

**Comment by utkarshmttl** [comment]
Done and I apologise for making this more work than it was worth.

**Pull request merged**
