### PR TITLE
Upload APK to the Play Store for older apps.

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
* Introduced the `upload_bundle` feature in the `info.json` file.
*  When it is set to true, it will upload the bundle to the Play Store. Otherwise, it will upload the APK.
* To adapt this feature we have modified our CI.
* For this change we have modified all the `info.json` files.
* To show this new feature we have updated our README file.

More reference https://github.com/kiwix/kiwix-android/pull/3633

### CODE REVIEW

**Comment by kelson42** [comment]
Old custom apps shoukd be uploaded as apk like before but new (from dwds) should be uploaded as bundle

**Comment by MohitMaliFtechiz** [comment]
> Old custom apps shoukd be uploaded as apk like before but new (from dwds) should be uploaded as bundle

@kelson42, @gouri-panda I have made the changes in CI and updated all the `info.json` files for this new change.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Thank you for the quick move

**Review by gouri-panda — APPROVED** [review]
@MohitMaliFtechiz Thanks!

**Pull request merged**
