### PR TITLE
Changed DWDS app name to all caps; DWDS is an acronym

### PR DESCRIPTION
**Pull request by gremid**

### CODE REVIEW

**Comment by kelson42** [comment]
@gremid OK, it seems here only the last commit is realy relevant here.

**Comment by gremid** [comment]
Indeed, only the last commit is relevant. The DWDS ZIM URL update was not merged into the `main` branch yet, so I was basing my PR on the `dwds`-tagged branch.

**Comment by kelson42** [comment]
@gouri-panda why the info.json does have an olf ZiM URL? It seems the json does not fit to what is released on the PlayStore?!

**Comment by gouri-panda** [comment]
@kelson42 Yes, we only update on the dwds tag because we haven't fully refactored all the code for the bundle. This is the update version of the tag. https://github.com/kiwix/kiwix-android-custom/blob/328c7b78c87931246a1694add9d29bfed4d64928/dwds/info.json#L3

**Comment by gouri-panda** [comment]
@gremid Same here too. We'll add this to our main branch later.

**Pull request closed without merging**
